### PR TITLE
chore:  Add in Snowflake db logo

### PR DESCRIPTION
**Pull request by instazackwu**
### Summary of Changes

Add in a logo for Snowflake database tables

### Tests

None, UI change

image
image

### Documentation

None

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes, including screenshots of any UI changes.
- [x] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by instazackwu** [comment]
cc @Alagappan adding in a logo for Snowflake database data

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
thanks @instazackwu , is Amundsen in prod now? and could you submit a pr to add your company to our user list (https://github.com/amundsen-io/amundsen#who-uses-amundsen) ? That will be super helpful, thanks!

**Comment by instazackwu** [comment]
> thanks @instazackwu , is Amundsen in prod now? and could you submit a pr to add your company to our user list (https://github.com/amundsen-io/amundsen#who-uses-amundsen) ? That will be super helpful, thanks!

Thanks Tao! We're making it official next week - I'll put in a PR to do that then :)

**Comment by Alagappan** [comment]
Great! Good to see the progress @instazackwu

**Pull request merged**
