### PR TITLE
chore: add license check action

### PR DESCRIPTION
**Pull request by feng-tao**
Signed-off-by: feng-tao <fengtao04@gmail.com>

### Summary of Changes

_Include a summary of changes then remove this line_

### Tests

_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes.
- [ ] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Review by Golodhros — DISMISSED** [review]
LGTM

**Comment by feng-tao** [comment]
@Golodhros any idea of why the FE unit test fails with this pr?

**Comment by Golodhros** [comment]
> @Golodhros any idea of why the FE unit test fails with this pr?

Yeah, you added some lines, so the lines where we have errors have change. To fix it, run `npm run betterer:update` on your CLI and commit the .bettererer.results file into the repo.

**Comment by feng-tao** [comment]
@Golodhros thanks, pr is updated with the updated lint file.

**Comment by feng-tao** [comment]
> What's the effect/how will this work?

if a new file is added without license header, the github action will fail.

**Pull request merged**
