### PR TITLE
fix: Make application docker image configurable

### PR DESCRIPTION
**Pull request by shuichiro-makigaki**
### Summary of Changes

This patch enables docker image users to add their custom config files easily.
Previous `setup.py install` had installed the application to system sites, and files added under `amundsen_application/` by `COPY` or `ADD` had not been recognized.

closes:  https://github.com/amundsen-io/amundsen/issues/190
related: https://github.com/amundsen-io/amundsen/issues/408

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes, including screenshots of any UI changes.
- [x] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [x] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [x] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by dorianj** [comment]
cc @verdan -- I know you've played with this recently

**Comment by dorianj** [comment]
@shuichiro-makigaki can you explain in more detail how this changes pip install flow? I understand how the `-e` option works for local installs, but I'm not sure I understand the benefit if for a built docker container?

The dockerignore for node modules make sense.

**Comment by shuichiro-makigaki** [comment]
OK, I should explain what this patch is.

When customizing the Amundsen frontend application, we usually create the following Dockerfile:

```Dockerfile
FROM amundsendev/amundsen-frontend:latest
COPY my_custom_config.py amundsen_application/
ENV  FRONTEND_SVC_CONFIG_MODULE_CLASS amundsen_application.my_custom_config.MyCustomConfig
```

This looks reasonable; however, the generated image does not run because of the ModuleNotFound error:

```
Registering post_exec action_log entry_point: logging_action_log = amundsen_application.log.action_log_callback:logging_action_log
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 576, in import_string
    module = __import__(module_name, globals(), locals(), [obj_name])
ModuleNotFoundError: No module named 'amundsen_application.my_custom_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "amundsen_application/wsgi.py", line 8, in <module>
    config_module_class=os.getenv('FRONTEND_SVC_CONFIG_MODULE_CLASS') or 'amundsen_application.config.LocalConfig')
  File "/usr/local/lib/python3.7/site-packages/amundsen_frontend-3.5.0-py3.7.egg/amundsen_application/__init__.py", line 50, in create_app
    app.config.from_object(config_module_class)
  File "/usr/local/lib/python3.7/site-packages/flask/config.py", line 170, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 585, in import_string
    ImportStringError, ImportStringError(import_name, e), sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_compat.py", line 147, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/utils.py", line 576, in import_string
    module = __import__(module_name, globals(), locals(), [obj_name])
werkzeug.utils.ImportStringError: import_string() failed for 'amundsen_application.my_custom_config.MyCustomConfig'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'amundsen_application' found in '/usr/local/lib/python3.7/site-packages/amundsen_frontend-3.5.0-py3.7.egg/amundsen_application/__init__.py'.
- 'amundsen_application.my_custom_config' not found.

Original exception:

ModuleNotFoundError: No module named 'amundsen_application.my_custom_config'
```

In this case, the `COPY` line in Dockerfile should be:

```Dockerfile
COPY my_custom_config.py /usr/local/lib/python3.7/site-packages/amundsen_frontend-3.5.0-py3.7.egg/amundsen_application/
```

But it's a little confusing.

In "editable-mode" (`-e`), customization to `/app` (e.g. adding `config.py`) is recognized and applied even after `setup.py install`.

It may be noteworthy that CSS is not affected in this patch because these static files (javascript, too) need to be `webpack`ed, which means running `webpack` again is required. The "Drop-in custom CSS" feature sounds interesting for me (and others), but it's out of scope in this Pull Request.

**Comment by shuichiro-makigaki** [comment]
Any update on this?

**Comment by dorianj** [comment]
I see, sorry for the slow response, but this makes sense.

**Review by dorianj — APPROVED** [review]

**Pull request merged**
