### PR TITLE
Update configuration.md

### PR DESCRIPTION
**Pull request by mkrajaci**
fix: the wrong link to documentation files

### Summary of Changes

_Include a summary of changes then remove this line_

### Tests

_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes. 
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by Golodhros** [comment]
@mkrajaci  You would need to follow the steps regarding the DCO sign off, check on the "details" link up there.

**Comment by mkrajaci** [comment]
I will check it, thanks @ttannis

**Comment by mkrajaci** [comment]
@ttannis could you help me? After entering this git push --force-with-lease origin pr/583 in the terminal I get an error: error: src refspec pr/583 does not match any
error: failed to push some refs to 'git@github.com:amundsen-io/amundsen.git'

**Comment by Golodhros** [comment]
> @ttannis could you help me? After entering this git push --force-with-lease origin pr/583 in the terminal I get an error: error: src refspec pr/583 does not match any
> error: failed to push some refs to '[git@github.com](mailto:git@github.com):amundsen-io/amundsen.git'
> I did all the requirements and even created new local branch

Interesting, I would guess the right command would be `git push --force-with-lease origin patch-1`

**Comment by mkrajaci** [comment]
This is the right command: git push --force-with-lease origin mkrajaci_patch_2 but after that a get another error:

ERROR: Permission to amundsen-io/amundsen.git denied to mkrajaci.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Golodhros** [comment]
> This is the right command: git push --force-with-lease origin mkrajaci_patch_2 but after that a get another error:
> 
> ERROR: Permission to amundsen-io/amundsen.git denied to mkrajaci.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 
> @Golodhros @ttannis do I need some special access rights for this commit?

What's the results of running `git remote -v` for you?

**Comment by mkrajaci** [comment]
> What's the results of running `git remote -v` for you?

origin	git@github.com:amundsen-io/amundsen.git (fetch)
origin	git@github.com:amundsen-io/amundsen.git (push)

**Comment by jornh** [comment]
@mkrajaci you need to `git remote add` your own fork where you have write permission (e.g. call it `mkrajaci`) then perform the force push against the patch-1 branch on that instead of `origin` so like:

```
git push --force-with-lease mkrajaci patch-1
```

It’s patch-1 because that’s what this PR is referencing as you see in the top of #583

**Comment by Golodhros** [comment]
Added on https://github.com/amundsen-io/amundsenfrontendlibrary/pull/676

**Pull request closed without merging**
