### PR TITLE
chore: bumped amundsen-common version

### PR DESCRIPTION
**Pull request by allisonsuarez**
### Summary of Changes

Bumped amundsen-common version which has fix for marshmallow-annotations version.

### Tests

n/a

### Documentation

n/a

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes.
- [ ] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by allisonsuarez** [comment]
🔨

**Comment by allisonsuarez** [comment]
🔨

**Comment by dorianj** [comment]
note that this PR is failing CI because `master` is broken -- once https://github.com/amundsen-io/amundsenfrontendlibrary/pull/797 lands, if you rebase off of that, this should pass

**Comment by allisonsuarez** [comment]
> note that this PR is failing CI because `master` is broken -- once #797 lands, if you rebase off of that, this should pass

oooh I didn't realize that thank you :)

**Review by feng-tao — APPROVED** [review]

**Pull request merged**
