### PR TITLE
build: Add Storybook

### PR DESCRIPTION
**Pull request by dorianj**
ref: https://github.com/amundsen-io/amundsen/issues/611

### Summary of Changes

Add storybook, an isolated dev environment for components.

### Tests

No tests. Would be nice to have some tests that storybook builds (so it's not accidentally broken), but can wait until storybook actually gets usage

### Documentation

I'm not sure which doc is appropriate?

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes. 
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by dorianj** [comment]
The biggest thing I'm worried about is the changes to the tsconfig, I'm not sure if that's reasonable or not.


Styles also appear to work (haven't tested heavily), but right now the Flag component is has Times New Roman, implying it's missing base styles. My understanding is that Storybook expects each component to include all needed styles, and including a base stylesheet is an anti-pattern, so this is "correct". If true it means we should change the patterns of how we style components, not change storybook config; if not true, I'm just wrong and I messed something up

**Comment by ttannis** [comment]
@dorianj thanks for the contribution. Can we add a piece of doc on this somewhere in https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/developer_guide.md? A brief callout that it exists and how to use it will suffice.

**Comment by Golodhros** [comment]
> @dorianj thanks for the contribution. Can we add a piece of doc on this somewhere in https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/docs/developer_guide.md? A brief callout that it exists and how to use it will suffice.

Good idea! I can take over that task!

**Comment by dorianj** [comment]
Sorry @Golodhros , I started on this before you commented -- https://github.com/amundsen-io/amundsenfrontendlibrary/pull/577 -- please edit to clarify anything you want, though!

**Comment by Golodhros** [comment]
> Sorry @Golodhros , I started on this before you commented -- #577 -- please edit to clarify anything you want, though!

Awesome! Added some comments!

**Pull request merged**
