### PR TITLE
feat: alphabetized badges

### PR DESCRIPTION
**Pull request by allisonsuarez**
Signed-off-by: Allison Suarez Miranda <asuarezmiranda@lyft.com>

### Summary of Changes

Organize badge list in alphabetical order rather than display badges in the order they are added.

### Tests

_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes.
- [ ] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Review by Golodhros — APPROVED** [review]
LGTM

**Comment by allisonsuarez** [comment]
> LGTM

I wonder why? 👀

**Comment by dorianj** [comment]
> > LGTM

> I wonder why? 👀

lol


is it possible to link to a ticket for things like this in the future? mostly curious about what the motivation was for the change? i suspect there's likely an internal lyft JIRA, and I think would be good for community to peek into the description there.

**Comment by allisonsuarez** [comment]
> > > LGTM
> 
> > I wonder why? 👀
> 
> lol
> 
> is it possible to link to a ticket for things like this in the future? mostly curious about what the motivation was for the change? i suspect there's likely an internal lyft JIRA, and I think would be good for community to peek into the description there.

No reason really, I just noticed it looked weird when you filtered by badges and there were multiple badges in multiple tables and they were not all organized the same.

**Pull request merged**
