### PR TITLE
[WIP] feat: add chart name in dashboard filter search

### PR DESCRIPTION
**Pull request by feng-tao**
Signed-off-by: feng-tao <fengtao04@gmail.com>

### Summary of Changes

Include chart in the dashboard filter search 

### Tests

_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes.
- [ ] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Review by Golodhros — APPROVED** [review]
LGTM

**Comment by feng-tao** [comment]
the chart is an array which the query string syntax in ES is not quite the same actually.

**Comment by ttannis** [comment]
> the chart is an array which the query string syntax in ES is not quite the same actually.

Can you clarify, is sending the chart name as a string like the other filters not working?

**Comment by feng-tao** [comment]
the chart in search index is a list which our current filter logic in search doesn't support. We should fix the search side first before move this pr forward.

**Pull request closed without merging**
