### PR TITLE
fix: make last run state in dashboard page optional

### PR DESCRIPTION
**Pull request by feng-tao**
Signed-off-by: feng-tao <fengtao04@gmail.com>

### Summary of Changes

For mode dashboard, we have last run state, for other dashboard type, we don’t have. So in https://github.com/amundsen-io/amundsenfrontendlibrary/blob/master/amundsen_application/static/js/pages/DashboardPage/index.tsx#L323, it will become none. then once it enters https://github.com/amundsen-io/amundsenfrontendlibrary/blob/f5149bcbfbc90013ef169095ed1148d3dc96e016/amundsen_application/static/js/components/common/ResourceStatusMarker/index.tsx#L44 , it throws exception and fails the whole page.

Make last run state optional which fixed the issue.

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes, including screenshots of any UI changes.
- [ ] PR adds unit tests, updates existing unit tests, **OR** documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public python functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes all tests documented in the [developer guide](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/developer_guide.md#testing)

### CODE REVIEW

**Comment by jornh** [comment]
Great fix, having a full failing page isn't fun! This is actually ONE step towards resolving https://github.com/amundsen-io/amundsen/issues/544 which has some discussion input in https://github.com/amundsen-io/amundsen/issues/544#issuecomment-656364931 we should consider. I'll discuss that later over there because that's more related to the metadata service API.

So, while at it why not tackle more (all?) of https://github.com/amundsen-io/amundsen/issues/544 - at the least for the "last run" related bits. Here's some reasoning:

If there is no `last run state` in the backend for a given dashboard it's also reasonable to assume there is no `last run` timestamp, therefore no `last successful run` time. This means for dashboard products that doesn't support the "last run" concept the whole section below "tags" is just useless UI noise as @jonhehir pointed out.

Following this it looks like we could just wrap both of the "last run" sections in the `hasLastRunState` condition and we're good.

**Review by Golodhros — APPROVED** [review]
LGTM

**Comment by feng-tao** [comment]
> amundsen-io/amundsen#544



> Great fix, having a full failing page isn't fun! This is actually ONE step towards resolving [amundsen-io/amundsen#544](https://github.com/amundsen-io/amundsen/issues/544) which has some discussion input in [amundsen-io/amundsen#544 (comment)](https://github.com/amundsen-io/amundsen/issues/544#issuecomment-656364931) we should consider. I'll discuss that later over there because that's more related to the metadata service API.
> 
> So, while at it why not tackle more (all?) of [amundsen-io/amundsen#544](https://github.com/amundsen-io/amundsen/issues/544) - at the least for the "last run" related bits. Here's some reasoning:
> 
> If there is no `last run state` in the backend for a given dashboard it's also reasonable to assume there is no `last run` timestamp, therefore no `last successful run` time. This means for dashboard products that doesn't support the "last run" concept the whole section below "tags" is just useless UI noise as @jonhehir pointed out.
> 
> Following this it looks like we could just wrap both of the "last run" sections in the `hasLastRunState` condition and we're good.

thanks @jornh for the issue. Make sense. Let me take a look and update the pr.

**Comment by feng-tao** [comment]
@Golodhros @allisonsuarez @jornh pr updated a bit

**Comment by feng-tao** [comment]
@jornh the section is hidden now. thanks for the pointer!

**Pull request merged**
